
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Enterprice_incidents.Ef
{

using System;
    using System.Collections.Generic;
    
public partial class View_Incidents
{

    public int Id { get; set; }

    public string FName { get; set; }

    public string SName { get; set; }

    public string LName { get; set; }

    public string ImportanceOfIncident { get; set; }

    public System.DateTime DateOfIncident { get; set; }

    public string IncidentName { get; set; }

    public int IncidentTypeId { get; set; }

}

}
